CREATE TABLE users(id SERIAL PRIMARY KEY, NAME VARCHAR, ADDRESS VARCHAR);

INSERT INTO users(NAME, ADDRESS) VALUES ('THIAGO', 'RUA 1');
INSERT INTO users(NAME, ADDRESS) VALUES ('EMIDIO', 'RUA 2');
INSERT INTO users(NAME, ADDRESS) VALUES ('CORREA', 'RUA 3');